Added partial class ProductController.Comment
ilmhub-uz/FurnitureShop pull request #446
Opened 2023-01-12 20:59 UTC by Botirjon29

review qivoradigan joyi

2023-01-13 14:00 UTC, javlonfattoev requested changes

2023-01-13 14:00 UTC, javlonfattoev commented on FurnitureShop/src/FurnitureShop.Client.Api/Services/ProductCommentService.cs
>          };
userid, createdat ...

2023-01-13 14:00 UTC, javlonfattoev commented on FurnitureShop/src/FurnitureShop.Client.Api/Controllers/ProductsController.Comment.cs
> +    [HttpPost]
post: products/12/comments

2023-01-13 14:00 UTC, javlonfattoev commented on FurnitureShop/src/FurnitureShop.Client.Api/Controllers/ProductsController.Comment.cs
> +    [ProducesResponseType(typeof(ProductCommentView), StatusCodes.Status200OK)]
get: products/12/comments/15

2023-01-13 14:00 UTC, javlonfattoev commented on FurnitureShop/src/FurnitureShop.Client.Api/Controllers/ProductsController.Comment.cs
> +    [ProducesResponseType(typeof(List<ProductCommentView>), StatusCodes.Status200OK)]
[HttpGet("{productId:guid}/comments")]

2023-01-17 14:14 UTC, Jamoliddin0710 approved these changes

2023-01-18 09:17 UTC, closed without merging